### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jumpjack** [floysh/DCC-green-pass-decoder#3]
Link **/tools/certs-scraper** is broken in https://github.com/floysh/DCC-green-pass-decoder/blob/main/docs/signature-validation.md 
And I think the page is incomplete, its title is Signature Validation, but it only explains how to download certificates. :-)

**Comment by floysh** [comment]
Thanks, I forgot to attach the files when I pushed the docs 😅 
I pushed them in one of the recent commits, so I'd consider this issue as closed
