### ISSUE TITLE
Its possible to create an script of encoding pipeline  described  in the readme?

### ISSUE THREAD

**Issue by JTorresConsulta** [floysh/DCC-green-pass-decoder#4]
It has helped me to understand more about how Qr reading works.

I am testing it with valid QR issued in Spain and your application returns error: "This is not an EU Digital COVID Certificate". What is the reason? 

I work as a programmer in a small laboratory in Spain. Until now we have been performing rapid antigen tests and it was not necessary to issue qr codes, but the results on paper were enough.  Now my boss has asked me to also generate the qr code with the test result so that the customer can use it, but the truth is that I can't find simple documentation for it. 

As I see you have experience with it, I wonder if you could give me some repository references or some help with it. 

I need my own script like this link: https://dgc.a-sit.at/ehn/
That is a private source and I cant set our owns certificates.

I want to do my best to avoid bugs and problems with my boss :)

Thank you very much.

**Comment by floysh** [comment]
Hard to tell why it fails without further information. What does the error message say?

There should be a set of official libraries for working with DCCs, but I never had to use it so I'm afraid I can't point you to them. Almost all the documentation I needed to make this app comes from the [EHN github profile](https://github.com/ehn-dcc-development). You may be interested in [ these examples ](https://github.com/ehn-dcc-development?q=sign&type=&language=&sort=) of implementations in python and node.
