### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by vmx** [floysh/DCC-green-pass-decoder#6]
Thanks for creating such a clean project to read out Covid certificates. I'd like to use it as a basis for a small webapp. Could you please add a license to your code to make that possible?

**Comment by maxstreifeneder** [comment]
Hi @floysh, 

thanks for your awesome work and clear description + coding! Highly appreciated.
I'd love to reuse your project in a sample app (non-commercial) and write a blogpost about it on our SAP community page. 

Would you be willing to add a license, preferably Apache 2.0 (or MIT) to your repo, so I can go on? :) 

I'm happy to share more details in case you are interested! 

Cheers and thanks a lot in advance,
Max

**Comment by floysh** [comment]
Hi @vmx, @maxstreifeneder

glad you enjoyed this hobby project :)
I released everything under the MIT license.

If your work will be publicly accessible, I'd love to take a look at it when it's released :)

**Comment by vmx** [comment]
@floysh great to hear. Sadly I didn't finish the project, I took too long ;) The idea was a simple website where people could upload their QR codes. It would then also extract information like the name on the client side. It would've been used for friends doing some group activity where valid certificates are a requirement.
