### ISSUE TITLE
Error scanning Safari

### ISSUE THREAD

**Issue by renaud-bxl** [floysh/DCC-green-pass-decoder#7]
Error Safari Version 15.1 (17612.2.9.1.20) Scanning does not work! Same problem with iphone and iPad ...

**Comment by renaud-bxl** [comment]
Remove "  navigator.vibrate(200),  " in bundle.js = OK !

**Comment by floysh** [comment]
Thanks. I tried to implement a fix for this issue in https://github.com/floysh/DCC-green-pass-decoder/commit/19f6481634b4da9256330c7563bdc20e78986d87 that doesn't remove the vibration for browsers that support it. Can you check if scanning works with Safari now? I'd check it myself but unfortunately I don't have an iOS device.

**Comment by renaud-bxl** [comment]
The problem persists ... 

The error code in Safari is as follows: Unhandled Promise Rejection: TypeError: navigator.vibrate is not a function. (In 'navigator.vibrate(200)', 'navigator.vibrate' is undefined)

I made a video for you to see the problem ... 

https://drive.google.com/file/d/1YZgD2uIW7dm8vZ-zG64CONcxcELf_vl6/view?usp=sharing

Error : 
Unhandled Promise Rejection: TypeError: navigator.vibrate is not a function. (In 'navigator.vibrate(200)', 'navigator.vibrate' is undefined)

**Comment by sensationunddesign** [comment]
Same problem here - unable to scan the QR code with iPhone … will there be a fix soon?

**Comment by floysh** [comment]
@renaud-bxl Thank you for taking the time and trouble to record this. I just noticed that I forgot to include some changes in the last commit. I made a new one with the missing fixes and now scanning should on Safari (and any other browser lacking support for navigator.vibrate()) too.
